### PR TITLE
[18.09 backport] Adds PartialLogMetadata to encode protobuf for logger plugins

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/moby/moby/pull/39038 for 18.09

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 @anusha-ragunathan ptal

**Comment by thaJeztah** [comment]
hm; possibly flaky; https://jenkins.dockerproject.org/job/Docker-PRs/53676/console

```
02:58:05 FAIL: docker_cli_swarm_test.go:275: DockerSwarmSuite.TestSwarmPublishAdd
02:58:05
02:58:05 [d0b179ec4be46] waiting for daemon to start
02:58:05 [d0b179ec4be46] daemon started
02:58:05
02:58:05 docker_cli_swarm_test.go:287:
02:58:05     c.Assert(err, checker.IsNil, check.Commentf("%s", out))
02:58:05 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4209e8e60), Stderr:[]uint8(nil)} ("exit status 1")
02:58:05 ... Error response from daemon: rpc error: code = Unknown desc = update out of sequence
02:58:05
02:58:05
02:58:05 [d0b179ec4be46] exiting daemon
```

experimental; also looks like some racy/flaky tests: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/44853/console

```
02:07:42 FAIL: docker_cli_run_test.go:1791: DockerSuite.TestRunInteractiveWithRestartPolicy
02:07:42
02:07:42 assertion failed:
02:07:42 Command:  /usr/local/cli/docker run -i --name test-inter-restart --restart=always busybox sh
02:07:42 ExitCode: 0
02:07:42 Error:    <nil>
02:07:42 Stdout:
02:07:42 Stderr:
02:07:42
02:07:42 Failures:
02:07:42 ExitCode was 0 expected 11

02:11:26 ----------------------------------------------------------------------
02:11:26 FAIL: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
02:11:26
02:11:26 docker_cli_start_test.go:194:
02:11:26     c.Assert(err, checker.NotNil)
02:11:26 ... value = nil
02:11:26
```

**Comment by anusha-ragunathan** [comment]
Code LGTM.

This change got me wondering about `partial` log support in our default jsonfile logger. I see no code in there that handles partial log data and assembles it as part of reader. @cpuguy83, thoughts?

**Comment by thaJeztah** [comment]
IIRC, the JSONfile logger uses the presence of a trailing `\n` as indication if the message was partial or not

**Comment by anusha-ragunathan** [comment]
Nevermind. https://github.com/moby/moby/blob/master/daemon/logger/jsonfilelog/jsonfilelog.go#L135 does process based on partial

**Comment by alexei38** [comment]
This change does not affect of jsonlogger, fluentd, journal, etc
In existing plug-ins PartialLogMetadata present

This change only affects external plugins. 
ex: https://github.com/cpuguy83/docker-log-driver-test

**Pull request merged**
