### PR TITLE
[19.03 backport] rootless: fix proxying UDP packets

### PR DESCRIPTION
**Pull request by AkihiroSuda**
backport https://github.com/moby/moby/pull/40317

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
CI failure seems unrelated

```
[2019-12-31T07:24:04.578Z] + bundleName=amd64

[2019-12-31T07:24:04.578Z] + echo Creating amd64-bundles.tar.gz

[2019-12-31T07:24:04.578Z] Creating amd64-bundles.tar.gz

[2019-12-31T07:24:04.578Z] + xargs tar -czf amd64-bundles.tar.gz

[2019-12-31T07:24:04.578Z] + find bundles -path */root/*overlay2 -prune -o -type f ( -name *-report.json -o -name *.log -o -name *.prof -o -name *-report.xml ) -print

[2019-12-31T07:24:04.578Z] find: ‘bundles’: No such file or directory

[2019-12-31T07:24:04.578Z] tar: Cowardly refusing to create an empty archive

[2019-12-31T07:24:04.578Z] Try 'tar --help' or 'tar --usage' for more information.

script returned exit code 123
```

**Comment by thaJeztah** [comment]
@AkihiroSuda can you rebase this one? docker-py tests should be fixed in this branch: we can merge after that

**Comment by thaJeztah** [comment]
triggered CI - I think it actually does a merge before running, so perhaps rebase is not needed. Fingers crossed

**Comment by AkihiroSuda** [comment]
rebased

**Comment by thaJeztah** [comment]
all green now; merging 👍

**Pull request merged**
