### PR TITLE
[19.03 backport] Testing and Jenkinsfile changes [step 1]

### PR DESCRIPTION
**Pull request by thaJeztah**
Not yet included:

- Migration from go-check to go-test
- Migration from gometalinter to golangci-lint

Backports of:

- https://github.com/moby/moby/pull/39430 Integration: remove redundant checks in IPVLAN tests
- https://github.com/moby/moby/pull/39431 Integration: remove redundant kernel version check for MACVlan
- https://github.com/moby/moby/pull/39468 integration-cli: remove ExecSupport check
- https://github.com/moby/moby/pull/39469 integration-cli: remove defaultSleepImage constant
- https://github.com/moby/moby/pull/39470 integration-cli: remove unused requirements utils
- https://github.com/moby/moby/pull/39500 Add (hidden) flags to set containerd namespaces
- https://github.com/moby/moby/pull/39509 integration: fix cleanup of raft data
- https://github.com/moby/moby/pull/39510 Don't log test initial test daemon ping failures
- https://github.com/moby/moby/pull/39517 Fix Microsecond -> Millisecond.
- https://github.com/moby/moby/pull/39516 DockerSwarmSuite lock portIndex to work around race
- https://github.com/moby/moby/pull/39552 Be more conservative for Windows in TestFrequency for Splunk 
- https://github.com/moby/moby/pull/39554 integration: run build session tests on non-experimental
- https://github.com/moby/moby/pull/39557 integration-cli: increase healthcheck timeout
- https://github.com/moby/moby/pull/39560 Retry service updates on out of sequence errors
- https://github.com/moby/moby/pull/39569 integration-cli: remove redundant "testrequires"
- https://github.com/moby/moby/pull/39603 Better logging for swarm tests
- https://github.com/moby/moby/pull/39604 hack: Remove inContainer check, it wasn't useful
- https://github.com/moby/moby/pull/39734 Fix some spelling mistakes
- https://github.com/moby/moby/pull/39802 integration: simplify parallel run destination
- https://github.com/moby/moby/pull/39724 Jenkinsfile: create junit.xml for integration tests
- https://github.com/moby/moby/pull/39743 Dockerfile: update CRIU to v3.12
- https://github.com/moby/moby/pull/39774 Fix testcase name
- https://github.com/moby/moby/pull/39800 pkg/term: refactor TestEscapeProxyRead
- https://github.com/moby/moby/pull/39804 integration: windows.ps1: turn defender error into a warning
- https://github.com/moby/moby/pull/39817 TestDispatch: refactor to use subtests again, and fix linting (structcheck)
- https://github.com/moby/moby/pull/39819 integration-cli: getContainerCount() fix trimming prefix
- https://github.com/moby/moby/pull/39831 Fix docker inspect for dutimgVersion
- https://github.com/moby/moby/pull/39836 hack/make/binary-daemon: fix some linting issues
- https://github.com/moby/moby/pull/39844 Fix some bashisms/non-standard comparisons in integration tests
- https://github.com/moby/moby/pull/39848 docker-py: skip flaky AttachContainerTest::test_attach_no_stream
- https://github.com/moby/moby/pull/39853 TestRunInteractiveWithRestartPolicy: use `icmd.RunCmd` instead `icmd.StartCmd`
- https://github.com/moby/moby/pull/39854 hack/ci/windows.ps1: explicitly set exit code to result of tests
- https://github.com/moby/moby/pull/39858 Jenkinsfile: create bundles for Windows stages
- https://github.com/moby/moby/pull/39863 Jenkinsfile hack for auto-cancellation
- https://github.com/moby/moby/pull/39876 integration-cli: update TestCreateWithWorkdir for Hyper-V isolation
- https://github.com/moby/moby/pull/39877 hack/ci/windows.ps1: add support for DOCKER_STORAGE_OPTS
- https://github.com/moby/moby/pull/39878 hack/ci/windows.ps1: stop tailing logs after stopping the daemon
- https://github.com/moby/moby/pull/39585 Dockerfile.windows: trim .0 from Go versions
- https://github.com/moby/moby/pull/39879 hack/ci/windows.ps1: fix Go version check (due to trailing .0)
- https://github.com/moby/moby/pull/39881 integration: TestInspect(): use swarm.RunningTasksCount
- https://github.com/moby/moby/pull/39884 Fix Service TTY test so signal handlers work
- https://github.com/moby/moby/pull/39886 integration-cli: don't load busybox image on every daemon start
- https://github.com/moby/moby/pull/39887 Windows: skip flaky TestLogBlocking
- https://github.com/moby/moby/pull/39900 Dockerfile: remove GOMETALINTER_OPTS
- https://github.com/moby/moby/pull/39910 integration-cli: Skip TestAPIImagesSaveAndLoad on RS3 and older
- https://github.com/moby/moby/pull/39917 Zap a fixed windows folder, add build number to folder inside
- https://github.com/moby/moby/pull/39968 awslogs: fix flaky TestLogBlocking unit test
- https://github.com/moby/moby/pull/39984 Jenkinsfile: move integration step cleanup to amd64 where it was intended to be

### Cherry-picks were clean; no conflicts

```bash
# https://github.com/moby/moby/pull/39430 Integration: remove redundant checks in IPVLAN tests
git cherry-pick -s -S -x 1e4bd2623a37b8083a7c5f8a93068be2c63f491c
git cherry-pick -s -S -x dae9bac6757af3027b06a983b8448ffa962cc071
git cherry-pick -s -S -x 93b28677bffcdaf299969c4ff1603b7d07b45fbc
git cherry-pick -s -S -x 4060a7026c0ffa2983ab1fa41d43da4937ef63c6

# https://github.com/moby/moby/pull/39431 Integration: remove redundant kernel version check for MACVlan
git cherry-pick -s -S -x 691eb142561818b0ca2255e2e340cbea6b91d80c
git cherry-pick -s -S -x 316e16618f8c794b8e56e223ed0bed15e1f4be24

# https://github.com/moby/moby/pull/39468 integration-cli: remove ExecSupport check
git cherry-pick -s -S -x 7204341950c6c8f0a66f9bb0b082217dc0ce6ddb

# https://github.com/moby/moby/pull/39469 integration-cli: remove defaultSleepImage constant
git cherry-pick -s -S -x 27f432ca57fb6d4d0409fc3c5358b74feae228cc

# https://github.com/moby/moby/pull/39470 integration-cli: remove unused requirements utils
git cherry-pick -s -S -x c887b09abc7d4ae149a9c314f74f9c351ac4cba2

# https://github.com/moby/moby/pull/39500 Add (hidden) flags to set containerd namespaces
git cherry-pick -s -S -x 24ad2f486d92681080a8e257760b047f8de2c71c

# https://github.com/moby/moby/pull/39509 integration: fix cleanup of raft data
git cherry-pick -s -S -x 6a64a4deecf5b7519d3748023765f79628059f80

# https://github.com/moby/moby/pull/39510 Don't log test initial test daemon ping failures
git cherry-pick -s -S -x 15675e28f1e3ba25f3abd099c14a7800c8bae2b8

# https://github.com/moby/moby/pull/39517 Fix Microsecond -> Millisecond.
git cherry-pick -s -S -x 5d818213ff3b9f8cda8e4fb3b071bef8fab782ad

# https://github.com/moby/moby/pull/39516 DockerSwarmSuite lock portIndex to work around race
git cherry-pick -s -S -x c096225e8ee6cb36e363ac38de4e4a566cf09918

# https://github.com/moby/moby/pull/39552 Be more conservative for Windows in TestFrequency for Splunk 
git cherry-pick -s -S -x a5c420ac54f07dbc84bcdea91b83364a25f1c921

# https://github.com/moby/moby/pull/39554 integration: run build session tests on non-experimental
git cherry-pick -s -S -x becd29c6651dffc253027e15f903ae7e7c918594

# https://github.com/moby/moby/pull/39557 integration-cli: increase healthcheck timeout
git cherry-pick -s -S -x 8c9362857f352548b94bc39c675d558b4da0d3b3

# https://github.com/moby/moby/pull/39560 Retry service updates on out of sequence errors
git cherry-pick -s -S -x 1de914695b7d0c9affc97a6da4198548da2f5f78

# https://github.com/moby/moby/pull/39569 integration-cli: remove redundant "testrequires"
git cherry-pick -s -S -x 7f37d99ef50b4046284ecb3c3b290319acf11405

# https://github.com/moby/moby/pull/39603 Better logging for swarm tests
git cherry-pick -s -S -x b0fe0dff7a5b7f70e2d08e59f4773c40e48e5c0d

# https://github.com/moby/moby/pull/39604 hack: Remove inContainer check, it wasn't useful
git cherry-pick -s -S -x f5cd8fdd446750a749182f3410adc6f1968053ca

# https://github.com/moby/moby/pull/39734 Fix some spelling mistakes
git cherry-pick -s -S -x f6226a2a56c38b790b59393ff4ce7f88f790c811

# https://github.com/moby/moby/pull/39802 integration: simplify parallel run destination
git cherry-pick -s -S -x 3262a69be6c582e4543199ddc54ebe2e306e3637

# https://github.com/moby/moby/pull/39724 Jenkinsfile: create junit.xml for integration tests
git cherry-pick -s -S -x f3be6b346f5300150dfa1de927880ea84440bb5b
git cherry-pick -s -S -x d2e00d62e244b293b5b2459942b3a55447c191f3
git cherry-pick -s -S -x f007b0150a1559ab3ba34cd81832c7c9b4e8f78f
git cherry-pick -s -S -x d723643dc38c18556ec5f7f0e97a8a594df545f7

# https://github.com/moby/moby/pull/39743 Dockerfile: update CRIU to v3.12
git cherry-pick -s -S -x 00ad0222cef8024f19394e2e9d5dc0e05f0ec982

# https://github.com/moby/moby/pull/39774 Fix testcase name
git cherry-pick -s -S -x c266d8fe563d4b1b65fb14a90da1b72f61b6310c

# https://github.com/moby/moby/pull/39800 pkg/term: refactor TestEscapeProxyRead
git cherry-pick -s -S -x 556d26c07d068d92fd896428ab4ac890554239d7

# https://github.com/moby/moby/pull/39804 integration: windows.ps1: turn defender error into a warning
git cherry-pick -s -S -x 31885181fcc0ca0cacd6c12f6c64ac553ff2bc2b

# https://github.com/moby/moby/pull/39817 TestDispatch: refactor to use subtests again, and fix linting (structcheck)
git cherry-pick -s -S -x a3f9cb5b635a76484a926289bfa4fc6feee1763a

# https://github.com/moby/moby/pull/39819 integration-cli: getContainerCount() fix trimming prefix
git cherry-pick -s -S -x 02c9b0674fe2cf43def3a1e625cab74a0db8136a

# https://github.com/moby/moby/pull/39831 Fix docker inspect for dutimgVersion
git cherry-pick -s -S -x 52a53e2587e34d45b1d4a9b7b7d307ad51c5b0b0

# https://github.com/moby/moby/pull/39836 hack/make/binary-daemon: fix some linting issues
git cherry-pick -s -S -x 70d36778252124d7cec0489ed98d1bac475d9727

# https://github.com/moby/moby/pull/39844 Fix some bashisms/non-standard comparisons in integration tests
git cherry-pick -s -S -x dbde4786e48531f095f9c3ecaff0f57b838abefc
git cherry-pick -s -S -x 32f1c651623421ee1ac480b200d34025a74436bb

# https://github.com/moby/moby/pull/39848 docker-py: skip flaky AttachContainerTest::test_attach_no_stream
git cherry-pick -s -S -x ce77a804b86886489fae47aa15a3ee5a0a8815e0

# https://github.com/moby/moby/pull/39853 TestRunInteractiveWithRestartPolicy: use `icmd.RunCmd` instead `icmd.StartCmd`
git cherry-pick -s -S -x e6fce00ec83df2f23523b836f647b8f3df97953f

# https://github.com/moby/moby/pull/39854 hack/ci/windows.ps1: explicitly set exit code to result of tests
git cherry-pick -s -S -x 8e8c52c4abe011a4cf3334da0726ef1fc0d17b14
git cherry-pick -s -S -x 7eb522a2350d759cf6a9aad493ac1b8ffc3d3335

# https://github.com/moby/moby/pull/39858 Jenkinsfile: create bundles for Windows stages
git cherry-pick -s -S -x 6ee61f54935d77d3d5667b4a3ba8f0be6c3de23d
git cherry-pick -s -S -x 1fbadd76b7ceab6e5bb683a7471f5cae8e715495

# https://github.com/moby/moby/pull/39863 Jenkinsfile hack for auto-cancellation
git cherry-pick -s -S -x 85bcc524eaa86ea5dde0c7214d15658587863a4c

# https://github.com/moby/moby/pull/39876 integration-cli: update TestCreateWithWorkdir for Hyper-V isolation
git cherry-pick -s -S -x ac9ef840ef94ff66266d3d8b9d32caf570d3b93f

# https://github.com/moby/moby/pull/39877 hack/ci/windows.ps1: add support for DOCKER_STORAGE_OPTS
git cherry-pick -s -S -x b6f596c4112818109441c84d313cf38fa06d6768

# https://github.com/moby/moby/pull/39878 hack/ci/windows.ps1: stop tailing logs after stopping the daemon
git cherry-pick -s -S -x e1636ad5fa1351c3edc20dd9006fb4d6f63c9f69

# https://github.com/moby/moby/pull/39585 Dockerfile.windows: trim .0 from Go versions
git cherry-pick -s -S -x c5bd6e3dc7680d6c683496f63dafb1f30f87eaa7

# https://github.com/moby/moby/pull/39879 hack/ci/windows.ps1: fix Go version check (due to trailing .0)
git cherry-pick -s -S -x 61450a651ba8fe4ef3cac284482a9495fc0b761d

# https://github.com/moby/moby/pull/39881 integration: TestInspect(): use swarm.RunningTasksCount
git cherry-pick -s -S -x f874f8b6fd10a180cc47d7a9829dff63233ee20c

# https://github.com/moby/moby/pull/39884 Fix Service TTY test so signal handlers work
git cherry-pick -s -S -x e6c5563ae9d083cc72fcf84796c542047ac0a299

# https://github.com/moby/moby/pull/39886 integration-cli: don't load busybox image on every daemon start
git cherry-pick -s -S -x 8fc23588f1aa14054f1134e60dd996220c595363
git cherry-pick -s -S -x ead3f4e7c8b7add7beb2de44649b38f41947180f

# https://github.com/moby/moby/pull/39887 Windows: skip flaky TestLogBlocking
git cherry-pick -s -S -x 6c75c862403c98138ab0f7811f6ba9113f9e5d61

# https://github.com/moby/moby/pull/39900 Dockerfile: remove GOMETALINTER_OPTS
git cherry-pick -s -S -x a464a3d51f89566b3e480d66903056004576cc85

# https://github.com/moby/moby/pull/39910 integration-cli: Skip TestAPIImagesSaveAndLoad on RS3 and older
git cherry-pick -s -S -x 5adaf52953476bf0ff612c8d78500e35821035bb

# https://github.com/moby/moby/pull/39917 Zap a fixed windows folder, add build number to folder inside
git cherry-pick -s -S -x 48662075434da5a13b1316df1ac7488a81e4cf0a

# https://github.com/moby/moby/pull/39968 awslogs: fix flaky TestLogBlocking unit test
git cherry-pick -s -S -x fd94bae0b8acc451a79667dd1cef4c583d532187

# https://github.com/moby/moby/pull/39984 Jenkinsfile: move integration step cleanup to amd64 where it was intended to be
git cherry-pick -s -S -x f3d8b8ae74804ba6a0386186c1c65bd1d556075a
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looking good; only one failure, which I think is still flaky; https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/engine/branches/PR-382/runs/1/nodes/195/log/?start=0


```
[2019-09-25T20:45:37.193Z] FAIL: docker_cli_swarm_test.go:1333: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] Creating a new daemon at: /go/src/github.com/docker/docker/bundles/test-integration/DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
[2019-09-25T20:45:37.193Z] [df3b3ef329025] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [df3b3ef329025] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [df3b3ef329025] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] Creating a new daemon at: /go/src/github.com/docker/docker/bundles/test-integration/DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
[2019-09-25T20:45:37.193Z] [dac804ef559d1] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [dac804ef559d1] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [dac804ef559d1] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] [dac804ef559d1] joining swarm manager [df3b3ef329025]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2478
[2019-09-25T20:45:37.193Z] Creating a new daemon at: /go/src/github.com/docker/docker/bundles/test-integration/DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
[2019-09-25T20:45:37.193Z] [da2168d1efc90] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [da2168d1efc90] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [da2168d1efc90] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] [da2168d1efc90] joining swarm manager [df3b3ef329025]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2479
[2019-09-25T20:45:37.193Z] [dac804ef559d1] Stopping daemon
[2019-09-25T20:45:37.193Z] [dac804ef559d1] exiting daemon
[2019-09-25T20:45:37.193Z] [dac804ef559d1] Daemon stopped
[2019-09-25T20:45:37.193Z] [dac804ef559d1] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [dac804ef559d1] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [dac804ef559d1] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] [da2168d1efc90] Stopping daemon
[2019-09-25T20:45:37.193Z] [da2168d1efc90] exiting daemon
[2019-09-25T20:45:37.193Z] [da2168d1efc90] Daemon stopped
[2019-09-25T20:45:37.193Z] [da2168d1efc90] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [da2168d1efc90] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [da2168d1efc90] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] [dac804ef559d1] Stopping daemon
[2019-09-25T20:45:37.193Z] [dac804ef559d1] exiting daemon
[2019-09-25T20:45:37.193Z] [dac804ef559d1] Daemon stopped
[2019-09-25T20:45:37.193Z] [dac804ef559d1] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [dac804ef559d1] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [dac804ef559d1] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] [da2168d1efc90] Stopping daemon
[2019-09-25T20:45:37.193Z] [da2168d1efc90] exiting daemon
[2019-09-25T20:45:37.193Z] [da2168d1efc90] Daemon stopped
[2019-09-25T20:45:37.193Z] [da2168d1efc90] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [da2168d1efc90] waiting for daemon to start
[2019-09-25T20:45:37.193Z] [da2168d1efc90] daemon started
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] docker_cli_swarm_test.go:1413:
[2019-09-25T20:45:37.193Z]     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
[2019-09-25T20:45:37.193Z] ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000937420), Stderr:[]uint8(nil)} ("exit status 1")
[2019-09-25T20:45:37.193Z] ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] 
[2019-09-25T20:45:37.193Z] [df3b3ef329025] Stopping daemon
[2019-09-25T20:45:37.193Z] [df3b3ef329025] exiting daemon
[2019-09-25T20:45:37.193Z] [df3b3ef329025] Daemon stopped
[2019-09-25T20:45:37.193Z] [dac804ef559d1] Stopping daemon
[2019-09-25T20:45:37.193Z] [dac804ef559d1] exiting daemon
[2019-09-25T20:45:37.193Z] [dac804ef559d1] Daemon stopped
[2019-09-25T20:45:37.193Z] [da2168d1efc90] Stopping daemon
[2019-09-25T20:45:37.193Z] [da2168d1efc90] exiting daemon
[2019-09-25T20:45:37.193Z] [da2168d1efc90] Daemon stopped
```


yup, still flaky; https://github.com/moby/moby/issues/38885

probably should've cherry-picked https://github.com/moby/moby/pull/39885 as well, so get more debugging on that issue, but can do that in a follow-up

**Comment by tiborvass** [comment]
@thaJeztah you're missing moby/moby#39984

**Comment by thaJeztah** [comment]
ah, good one; think it wasn't merged yet when I created my list of things to backport; added it to https://github.com/docker/engine/pull/383

**Comment by thaJeztah** [comment]
hm perhaps I need it in this one after all to get CI green (the other one is green now)

**Pull request merged**
