### PR TITLE
[19.03 backport] bump libnetwork to 92d1fbe1eb0883cf11d283cea8e658275146411d

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to [FIELD-211]
relates to [ENGCORE-960]
relates to [ENGCORE-692]

(docker/libnetwork#2415 / docker/libnetwork#2415)
backports of:

- https://github.com/moby/moby/pull/39054 bump libnetwork. vishvananda/netlink 1.0, vishvananda/netns
- https://github.com/moby/moby/pull/39423 Update modules to support riscv64
- https://github.com/moby/moby/pull/39633 bump libnetwork to 09cdcc8c0eab3946c2d70e8f6225b05baf1e90d1

### https://github.com/moby/moby/pull/39054 bump libnetwork. vishvananda/netlink 1.0, vishvananda/netns

full diffs:

- https://github.com/docker/libnetwork/compare/fc5a7d91d54cc98f64fc28f9e288b46a0bee756c...62a13ae87c6058bdc000fcccbf7e0f9f7525e2a9
- https://github.com/vishvananda/netlink/compare/b2de5d10e38ecce8607e6b438b6d174f389a004e...v1.0.0
- https://github.com/vishvananda/netns/compare/604eaf189ee867d8c147fafc28def2394e878d25...13995c7128ccc8e51e9a6bd2b551020a27180abd

notable changes in libnetwork:

- docker/libnetwork#2366 Bump vishvananda/netlink to 1.0.0
  - partially addresses https://github.com/moby/moby/issues/39404 Fork and update dependency of github.com/vishvananda/netns
  - fixes https://github.com/moby/moby/issues/39184 Please update vishvananda/netns for ppc64 support
- docker/libnetwork#2339 controller: Check if IPTables is enabled for arrangeUserFilterRule
  - fixes docker/libnetwork#2158 dockerd when run with --iptables=false modifies iptables by adding DOCKER-USER
  - fixes moby/moby#35777 With iptables=false dockerd still creates DOCKER-USER chain and rules
  - fixes docker/for-linux#136 dockerd --iptables=false adds DOCKER-USER chain and modify FORWARD chain anyway
- docker/libnetwork#2394 Make DNS records and queries case-insensitive
  - fixes moby/moby#28689 Embedded DNS is case-sensitive
  - fixes moby/moby#21169 hostnames with new networking are case-sensitive

### https://github.com/moby/moby/pull/39423 Update modules to support riscv64

Updating projects using libraries that were recently updated to support Risc-V architecture.

Go upstream work is tracked on: golang/go#27532

Risc-V software support tracker on https://github.com/carlosedp/riscv-bringup

### https://github.com/moby/moby/pull/39633 bump libnetwork to 09cdcc8c0eab3946c2d70e8f6225b05baf1e90d1 

full diff: https://github.com/docker/libnetwork/compare/83d30db53600b9c084d35fb1d560f97f8b34ab24...09cdcc8c0eab3946c2d70e8f6225b05baf1e90d1

changes included:

- docker/libnetwork#2416 Fix hardcoded AF_INET for IPv6 address handling
- docker/libnetwork#2411 Macvlan network handles netlabel.Internal wrong
  - fixes docker/libnetwork#2410 Macvlan network handles netlabel.Internal wrong
- docker/libnetwork#2414 Allow network with --config-from to be --internal
  - fixes docker/libnetwork#2413 Network with --config-from does not honor --internal
- docker/libnetwork#2351 Use fewer modprobes
  - relates to moby/moby#38930 Use fewer modprobes
- docker/libnetwork#2415 Support dockerd and system restarts for ipvlan and macvlan networks
  - carry of docker/libnetwork#2295 phantom ip/mac vlan network after a powercycle
  - fixes docker/libnetwork#1743 Phantom docker network

#### bump libnetwork to 92d1fbe1eb0883cf11d283cea8e658275146411d

full diff: https://github.com/docker/libnetwork/compare/09cdcc8c0eab3946c2d70e8f6225b05baf1e90d1...92d1fbe1eb0883cf11d283cea8e658275146411d

relevant changes included (omitting some changes that were added _and_ reverted in this bump):

- docker/libnetwork#2433 Fix parseIP error when parseIP before get AddressFamily
  - fixes docker/libnetwork#2431 parseIP Error ip=[172 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
  - https://github.com/docker/libnetwork/issues/2289
  - this was a regression introduced in docker/libnetwork#2416 Fix hardcoded AF_INET for IPv6 address handling
- docker/libnetwork#2440 Bump hashicorp go-sockaddr v1.0.2, go-multierror v1.0.0

#### bump hashicorp/go-multierror v1.0.0, add errwrap v1.0.0

full diff: https://github.com/hashicorp/go-multierror/compare/fcdddc395df1ddf4247c69bd436e84cfa0733f7e...v1.0.0

#### bump hashicorp/go-sockaddr v1.0.2

full diff: https://github.com/hashicorp/go-sockaddr/compare/6d291a969b86c4b633730bfc6b8b9d64c3aafed9...v1.0.2

Relevant changes:
- hashicorp/go-sockaddr#25 Add android os
- hashicorp/go-sockaddr#28 Add go.mod

[FIELD-211]: https://docker.atlassian.net/browse/FIELD-211

[ENGCORE-960]: https://docker.atlassian.net/browse/ENGCORE-960

[ENGCORE-692]: https://docker.atlassian.net/browse/ENGCORE-692

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @arkodg @selansen @andrewhsu PTAL if all of these are ok for backporting (looks like they're all fixes, but could use some eyes to double-check, also to see if there's risk involved)

**Comment by thaJeztah** [comment]
@selansen I see there's an open issue for adding an integration test for this: https://github.com/moby/moby/issues/39511

**Comment by arkodg** [comment]
@thaJeztah we probably need to merge https://github.com/docker/libnetwork/pull/2433 in libnetwork first,  which fixes a regression caused by https://github.com/docker/libnetwork/pull/2416/

**Comment by thaJeztah** [comment]
ok; marking this as WIP

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/39855 to update libnetwork with the fix

**Comment by trapier** [comment]
HPE has been pinging customer support daily to ask what 19.03 version this will be in.  Given this hasn't yet merged, I assume it's going to miss the forthcoming patch?

**Comment by thaJeztah** [comment]
perhaps still possible if I get this reviewed

**Comment by thaJeztah** [comment]
@kolyshkin @arkodg @andrewhsu PTAL

**Pull request merged**
