### PR TITLE
[18.09 backport] projectquota: protect concurrent map access (ENGCORE-920)

### PR DESCRIPTION
**Pull request by kolyshkin**
This is a backport of
* https://github.com/moby/moby/pull/39327 allow dockerd builds without cgo
* https://github.com/moby/moby/pull/39644 projectquota: protect concurrent map access (ENGCORE-920)
 
to address

* https://github.com/moby/moby/issues/39643 Docker daemon crashes (again) with "fatal error: concurrent map read and map write"

Clean cherry-pick, no issues (https://github.com/moby/moby/pull/39327 is required solely for a clean cherry-pick)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Was this updated with the last version? https://jenkins.dockerproject.org/job/Docker-PRs/55137/console

```
22:27:54 fatal error: sync: Unlock of unlocked RWMutex
22:27:54 
22:27:54 goroutine 12 [running]:
```

Looks like it's cherry-picking https://github.com/docker/docker/commit/b845a747f9c0e41e93741e2cc3646f7996302e98 instead of https://github.com/docker/docker/commit/1ac0a66a64a906911d0708cd0e5fa397a2f0b595

**Comment by kolyshkin** [comment]
fixed to switch to last version of upstream commit

**Comment by thaJeztah** [comment]
Janky failure should not be related https://jenkins.dockerproject.org/job/Docker-PRs/55220/console

```
20:50:13 FAIL: docker_cli_start_test.go:190: DockerSuite.TestStartReturnCorrectExitCode
20:50:13 
20:50:13 assertion failed: expected an error, got nil
```

**Comment by kolyshkin** [comment]
> 20:50:13 FAIL: docker_cli_start_test.go:190: DockerSuite.TestStartReturnCorrectExitCode

is https://github.com/moby/moby/issues/38521

**Pull request merged**
