### PR TITLE
[18.06] Bump swarmkit to include task reaper fixes and more metrics.

### PR DESCRIPTION
**Pull request by thaJeztah**
cherry-pick of https://github.com/moby/moby/pull/37399 for 18.06. cherry pick was clean, no conflicts

This includes the following behavior-modifying PRs:

- docker/swarmkit#2673
- docker/swarmkit#2669
- docker/swarmkit#2675
- docker/swarmkit#2664

### CODE REVIEW

**Comment by thaJeztah** [comment]
oh whoops; duplicate of https://github.com/docker/engine/pull/12

**Comment by thaJeztah** [comment]
hm; I see that one was a "custom" PR, not a cherry-pick; perhaps we should use this one still. Let me keep it open so that we can decide which one to take @cyli @tiborvass

**Comment by cyli** [comment]
@thaJeztah Ah sorry, I think I did not do `git cherry-pick -x`

**Comment by thaJeztah** [comment]
ping @cyli @andrewhsu @vdemeester @tiborvass PTAL

**Pull request merged**
