### PR TITLE
[19.03 backport] Update Microsoft/go-winio v0.4.14

### PR DESCRIPTION
**Pull request by thaJeztah**
backports of:

- https://github.com/moby/moby/pull/39124 Revendor go-winio
- https://github.com/moby/moby/pull/39679 Update Microsoft/go-winio v0.4.14

### CODE REVIEW

**Comment by thaJeztah** [comment]
@jterry75 @kevpar  @ddebroy PTAL

**Comment by thaJeztah** [comment]
vendor is failing because we didn't backport the vndr update from https://github.com/moby/moby/pull/39216 yet;

```
15:20:09 The result of vndr differs
15:20:09 
15:20:09  D vendor/github.com/Microsoft/go-winio/go.mod
15:20:09 
```

I'll have to rebase this one once https://github.com/docker/engine/pull/316 is merged

**Comment by thaJeztah** [comment]
From the PR:

> This is to fix a regression here: https://github.com/moby/moby/blob/master/daemon/graphdriver/windows/windows.go#L343 if the fallback code needs to call `vhd.DetachVhd` due to in-use the call with fail with `E_INVALID_PARAMETER` due to the vendored update to go-winio previously.

**Comment by ddebroy** [comment]
LGTM

**Pull request merged**
