### PR TITLE
[WIP][18.09 backport] overlay2: fix for Linux 4.19 (metacopy=off)

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/moby/moby/pull/38296 for 18.09
fix https://github.com/docker/for-linux/issues/480 for 18.09

```
git checkout -b 18.09_backport_overlay_metacopy ce-engine/18.09 
git cherry-pick -s -S -x a896b5415034cc75b7d3f13a781082f8f638f6a5
```

cherry-pick was clean; no conflicts

Linux Kernel v.4.19 introduces a new overlay feature called metadata
copy up (or just metacopy). Quoting kernel docs:

> When metadata only copy up feature is enabled, overlayfs will only copy
> up metadata (as opposed to whole file), when a metadata specific operation
> like chown/chmod is performed. Full file will be copied up later when
> file is opened for WRITE operation.

Until the kernel commit d5791044d2e574 ("ovl: Provide a mount option
metacopy=on/off...") this feature was disabled by default.

Unfortunately for Docker, since the above commit the feature is on
by default in case CONFIG_OVERLAY_FS_METACOPY=y is set (which is up
to a distro vendor), and it is not working with the naive diff driver:
docker build leads to errors like this:

> dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Invalid cross-device link

To fix, use the same mechanism as in commit 8422d85087bfa
("overlay2: use index=off if possible"), i.e. check if the
kernel module parameter is present, and if it is, add
`metacopy=off` to mount options.

Fixes https://github.com/docker/for-linux/issues/480

### CODE REVIEW

**Comment by kolyshkin** [comment]
janky got a test timeout in `TestAuthZPluginV2BadManifestFailsDaemonStart`, probably just some flakyness so need to be restarted.

**Comment by thaJeztah** [comment]
kicked janky

**Comment by thaJeztah** [comment]
Marked this "WIP", per https://github.com/moby/moby/pull/38296#issuecomment-445355210

**Comment by thaJeztah** [comment]
Closing this, per https://github.com/moby/moby/pull/38296#issuecomment-471114404

> This is a kernel bug that is fixed in kernel >= 4.19.11

**Pull request closed without merging**
