### PR TITLE
[18.09 backport] Windows:Allow process isolation

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/moby/moby/pull/38000 for 18.09

fixes https://github.com/moby/moby/issues/27524 
fixes https://github.com/moby/moby/issues/37873
fixes https://github.com/docker/for-win/issues/1822
closes https://github.com/moby/moby/pull/37065
closes https://github.com/moby/moby/pull/27730

```
git checkout -b 18.09_backport_processandiot ce-engine/18.09
git cherry-pick -s -S -x c907c2486c0850030f8ac1819ac8c87631472c68
```

cherry-pick was clean, no conflicts

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @andrewhsu PTAL

**Comment by chlowell** [comment]
@thaJeztah will this make it into 18.09?

**Comment by thaJeztah** [comment]
@chlowell unfortunately, it did not make it for the 18.09.0 release (QA was already too far into verifying the release), but there probably will be a 18.09.1 patch release and, if approved, it may find its way into that release.

**Comment by t0p4** [comment]
@thaJeztah I've built docker engine with your patch on Windows 10 1809 and run with --isolation=process but no succes. Container don't run

**Comment by justincormack** [comment]
@t0p4 what error message do you get? You need to run a container with a 1809 base image, I think some should be available now.

**Comment by t0p4** [comment]
@justincormack Host and container are  10.0.17763.134. Hang with status created. No errors

**Comment by t0p4** [comment]
cool solution, it's work

**Comment by LeSanchez** [comment]
Does it mean that on windows 1809 it will be possible to run any container based on previous windows server images (2016, 1709, etc) in process isolation mode?

**Comment by thaJeztah** [comment]
No, process isolation requires the base image to match the host version of Windows (this is due to Windows not having a stable kernel API)

**Comment by LeSanchez** [comment]
@thaJeztah ok and this means i could have windows 10 1709 and run a container windows servercore 1709 rght? It bridges the gap between server and client?

**Comment by nelsonjchen** [comment]
Does this work in Windows 10 Home? I'm kind of curious.

**Comment by thaJeztah** [comment]
@nelsonjchen Windows 10 Home is not supported for Docker Desktop (requires "pro"), nor Docker EE, so not sure if it will run ok (i.e., it's untested).

**Comment by thaJeztah** [comment]
@LeSanchez I _think_ that works yes (but disclaimer: I'm  not on Windows myself, so take it with a grain of salt 😅)

**Comment by justincormack** [comment]
@nelsonjchen we don't know, also kind of curious, it may still require other pieces that are not shipped in Home but I don't know anyone who has tried it yet.

**Comment by LeSanchez** [comment]
@thaJeztah Thanks!

**Comment by nelsonjchen** [comment]
🔨 ⚰️ 

Windows 10 Home 1809 doesn't have the containers feature that can be installed like Pro. That was expected. I guess that's that.

**Pull request merged**
