### PR TITLE
[18.09] Bump Go to  1.11.12

### PR DESCRIPTION
**Pull request by kolyshkin**
### Bump Go to 1.11.12
go1.11.12 (released 2019/07/08) includes fixes to the compiler and the linker.
See the Go 1.11.12 milestone on our issue tracker for details:
* https://github.com/golang/go/issues?q=milestone%3AGo1.11.12  

Full diff: https://github.com/golang/go/compare/go1.11.11...go1.11.12

### Misc Dockerfile improvements
* moby#37953 Dockerfile.e2e: simplify apk calls
* moby#39537 Dockerfile: Use APT_MIRROR for security.debian.org as well
* moby#39548 Dockerfile: use GO_VERSION build-arg for overriding Go version
* moby#39585 Dockerfile.windows: trim .0 from Go versions
* moby#39586 Windows: fix Golang version checks for GO_VERSION build-arg
* moby#39582 Pin Dockerfile to -stretch variant because it's bust'd

### CODE REVIEW

**Comment by thaJeztah** [comment]
Need to cherry-pick some other changes

- https://github.com/moby/moby/pull/39548 Dockerfile: use GO_VERSION build-arg for overriding Go version
- https://github.com/moby/moby/pull/39585 Dockerfile.windows: trim .0 from Go versions
- https://github.com/moby/moby/pull/39586 Windows: fix Golang version checks for GO_VERSION build-arg
- https://github.com/moby/moby/pull/39582 Pin Dockerfile to -stretch variant because it's bust'd

```
 22:45:29 E: Unable to locate package libprotobuf-c0-dev
```

**Comment by thaJeztah** [comment]
ping @kolyshkin ^^

**Comment by kolyshkin** [comment]
Also
* https://github.com/moby/moby/pull/37953 Dockerfile.e2e: simplify apk calls
* https://github.com/moby/moby/pull/39537 Dockerfile: Use APT_MIRROR for security.debian.org as well

**Comment by kolyshkin** [comment]
@thaJeztah PTAL

**Comment by thaJeztah** [comment]
Is this the failure?

```
20:13:55 /go/src/github.com/docker/docker/hack/ci/janky: line 7: GIT_SHA1: unbound variable
20:13:57 Build step 'Execute shell' marked build as failure
```

@seemethere @andrewhsu ?

**Comment by andrewhsu** [comment]
I think we need this cherry-picked to the 18.09 codeline: https://github.com/moby/moby/pull/39529/commits/bd5c5373f1b930e6a4f29a77606fa687c2200aeb

**Comment by andrewhsu** [comment]
I've added the environment variable `GIT_SHA1` back to the jenkins job for now.

**Comment by kolyshkin** [comment]
> I think we need this cherry-picked to the 18.09 codeline: moby@bd5c537

There's no `Jenkinsfile` in 18.09 so it's impossible to backport

**Comment by kolyshkin** [comment]
Looks like this one is ready to merge, except I don't know how to restart janky CI

**Comment by kolyshkin** [comment]
Janky failure is

> 02:39:07.872 Step 24/29 : COPY --from=builder /output/docker-frozen-images /docker-frozen-images
> 02:39:08.916 invalid from flag value builder: pull access denied for builder, repository does not exist or may require 'docker login'
> 02:39:08.925 Build step 'Execute shell' marked build as failure

Did we really broke something?

**Comment by kolyshkin** [comment]
Yes we did, looks like commit 697cd3d85dbfb73c68a7b0c7646b6b85a665799e changes `base` to `builder`. My bad. Fixed, force-pushed.

**Comment by thaJeztah** [comment]
Only failures are https://jenkins.dockerproject.org/job/Docker-PRs-experimental/46361/console  experimental:

```
06:39:37 FAIL: docker_cli_run_test.go:1792: DockerSuite.TestRunInteractiveWithRestartPolicy
06:39:37 
06:39:37 assertion failed: 
06:39:37 Command:  /usr/local/cli/docker run -i --name test-inter-restart --restart=always busybox sh
06:39:37 ExitCode: 0
06:39:37 Error:    <nil>
06:39:37 Stdout:   
06:39:37 Stderr:   
06:39:37 
06:39:37 Failures:
06:39:37 ExitCode was 0 expected 11
```

Janky https://jenkins.dockerproject.org/job/Docker-PRs/55270/console

```
07:46:52 FAIL: docker_cli_start_test.go:190: DockerSuite.TestStartReturnCorrectExitCode
07:46:52 
07:46:52 assertion failed: expected an error, got nil
```

**Pull request merged**
