### PR TITLE
Update http_helpers.go

### PR DESCRIPTION
**Pull request by AlexShu88**
Signed-off-by: Alex Shu <ashu@mirantis.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for contributing, but this repository is no longer used; development is done in the upstream https://github.com/moby/moby repository, which is also where the release branches for docker 19.03 and up are now maintained

**Comment by AlexShu88** [comment]
@thaJeztah .  I can see the http response code is -1, but I don't know what cause the response code to be -1 , do you have any idea how to address this issue ? 
cua005324d/dsinfo/logs/ucp-swarm-manager.log:2020-09-30T18:52:46.084055462-04:00 time="2020-09-30T22:52:46Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1

**Comment by thaJeztah** [comment]
@AlexShu88 hmm... no, without the associated API call that was made (that returned the `-1` HTTP status, that would be difficult to tell

**Comment by AlexShu88** [comment]
Thank you, @thaJeztah , could you please kindly instruct me which code call the function of FromStatusCode? I can see the origin of the error log is from this function, I have to trace the error source reversely from this function. but I am pretty fresh to docker code. 

func FromStatusCode(err error, statusCode int) error {
	if err == nil {
		return err
	}
	switch statusCode {
	case http.StatusNotFound:
		err = NotFound(err)
	case http.StatusBadRequest:
		err = InvalidParameter(err)
	case http.StatusConflict:
		err = Conflict(err)
	case http.StatusUnauthorized:
		err = Unauthorized(err)
	case http.StatusServiceUnavailable:
		err = Unavailable(err)
	case http.StatusForbidden:
		err = Forbidden(err)
	case http.StatusNotModified:
		err = NotModified(err)
	case http.StatusNotImplemented:
		err = NotImplemented(err)
	case http.StatusInternalServerError:
		if !IsSystem(err) && !IsUnknown(err) && !IsDataLoss(err) && !IsDeadline(err) && !IsCancelled(err) {
			err = System(err)
		}
	default:
		logrus.WithFields(logrus.Fields{
			"module":      "api",
			"status_code": fmt.Sprintf("%d", statusCode),
		}).Debugf("FIXME: Got an status-code for which error does not match any expected type!!!: %d", statusCode)

		switch {
		case statusCode >= 200 && statusCode < 400:
			// it's a client error
		case statusCode >= 400 && statusCode < 500:
			err = InvalidParameter(err)
		case statusCode >= 500 && statusCode < 600:
			err = System(err)
		default:
			err = Unknown(err)
		}
	}
	return err

**Comment by thaJeztah** [comment]
It's used in the API client when connecting to the Docker Engine API;

- when calling the `/_ping` endpoint; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/ping.go#L50-L66
- and for any other (GET/POST/PUT/DELETE) request made to the API; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L108-L119

So I suspect that the API that's connected to (which in UCP's case I _think_ is a proxy that wraps the actual "Docker Engine API") returns a `-1` status code, so if you know what call is made that produces the warning, you coud try to look into what causes UCP to return that status code.

Also note that the message should only be printed if log-level is "DEBUG", which should not be the default

**Comment by AlexShu88** [comment]
Thank you very much, @thaJeztah , exactly,  it did emerge in all DEBUG logs in UCP-Swarm-Manager,  ucp-proxy  and ucp-controller,

in  moby/client/request.go , i find that statusCode is initialized to be -1 in function doRequest,  

func (cli *Client) doRequest(ctx context.Context, req *http.Request) (serverResponse, error) {
	serverResp := serverResponse{statusCode: -1, reqURL: req.URL}

but later , maybe due to resp ==nil,  statusCode still keeps -1,

if resp != nil {
		serverResp.statusCode = resp.StatusCode
		serverResp.body = resp.Body
		serverResp.header = resp.Header
	}
	return serverResp, nil

could you please kindly instruct me under which condition, will  cause the server resp== nil ?

logs/ucp-controller.log:2020-05-05T20:32:04.178271877Z {"level":"debug","module":"api","msg":"FIXME: Got an status-code for which error does not match any expected type!!!: -1","status_code":"-1","time":"2020-05-05T20:32:04Z"}

logs/ucp-swarm-manager.log:2020-05-05T20:49:26.912110983Z time="2020-05-05T20:49:26Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1

logs/ucp-proxy.log:2020-05-04T16:36:49.152023815Z time="2020-05-04T16:36:49Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1

**Comment by thaJeztah** [comment]
> could you please kindly instruct me under which condition, will cause the server resp== nil ?

It think it would only be `nil` if a connection error occurred; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L125-L126

```go
req = req.WithContext(ctx)
resp, err := cli.client.Do(req)
if err != nil {
```


`cli.client.Do(req)` is `net/http/client.Do()`; https://github.com/golang/go/blob/go1.13.15/src/net/http/client.go#L508-L510, which documents;

```go
// If the returned error is nil, the Response will contain a non-nil
// Body which the user is expected to close. If the Body is not both
// ...
```

So it should only be `nil` if an error occurred. In situations where an error occurs, for example in; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L113-L116

```go
resp, err := cli.doRequest(ctx, req)
if err != nil {
	return resp, errdefs.FromStatusCode(err, resp.statusCode)
}
```

If no error is returned, we check the response to see if there's an error; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L117-L118, which excludes success responses; 

```go
func (cli *Client) checkResponseErr(serverResp serverResponse) error {
	if serverResp.statusCode >= 200 && serverResp.statusCode < 400 {
		return nil
	}
```

I there's no error, `FromStatusCode` won't handle the http-status, https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/errdefs/http_helpers.go#L76-L80

So the only way this could be produce is if _somewhere_ in your code, `FromStatusCode` is called with a `nil` error (e.g., if it's called without checking `checkResponseErr`)

**Review by ParasU1986 — COMMENTED** [review]
#

> 

> [](gh pr checkout 458)

**Pull request closed without merging**
