### PR TITLE
[19.03 backport] builder-next: userns remap support and honor daemon's DNS config 

### PR DESCRIPTION
**Pull request by thaJeztah**
obsoletes https://github.com/docker/engine/pull/290
closes https://github.com/docker/engine/pull/290

fixes https://github.com/moby/buildkit/issues/943 for 19.03
fixes https://github.com/moby/moby/issues/39442 for 19.03

Allow buildkit builds with `userns-remap` flag, and to use the DNS that's configured on the daemon

- revert the vendor bump from https://github.com/docker/engine/pull/312 (re-applied as last commit)
- https://github.com/moby/moby/pull/39349 builder-next: userns remap support
- https://github.com/moby/moby/pull/39444 builder-next: reset identitymapping if empty
- https://github.com/moby/moby/pull/39329 build: buildkit now honors daemon's DNS config
- https://github.com/moby/moby/pull/39216 bump vndr to f5ab8fc5f, and revendor
- https://github.com/moby/moby/pull/39687 vendor: update buildkit to f5a55a95

```
# revert the vendor bump from https://github.com/docker/engine/pull/312 (re-applied as last commit)
git revert -s -S eaa83640faf3fff1944a3faf868ca284bf5f89c7

# https://github.com/moby/moby/pull/39349 builder-next: userns remap support
git cherry-pick -s -S -x 07b3aac9020f1f5e3f7af0cb691cfb6e2189c089 5c484890e0b2612b33dd817ca21ab77c5d00fa44

# https://github.com/moby/moby/pull/39444 builder-next: reset identitymapping if empty
git cherry-pick -s -S -x 0bdcc60c4c8f0587af610c1cbf08e7fa6dac750e

# https://github.com/moby/moby/pull/39329 build: buildkit now honors daemon's DNS config
git cherry-pick -s -S -x a1cdd4bfcc515a862e18ac123836fcaa05d09b32

# https://github.com/moby/moby/pull/39216 bump vndr to f5ab8fc5f, and revendor
git cherry-pick -s -S -x 0a3c9b935c20bddce8d51b277510f13b94bfea92

# https://github.com/moby/moby/pull/39687 vendor: update buildkit to f5a55a95
git cherry-pick -s -S -x c60e53a274b348e9d922447df0a5344eb8e204ee
```

All cherry-picks were clean; no conflicts

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tonistiigi @tiborvass @andrewhsu PTAL

**Comment by tonistiigi** [comment]
@thaJeztah why the vndr bump?

**Comment by kolyshkin** [comment]
Revert of #312 was done for the sake of clean cherry-picks

**Comment by thaJeztah** [comment]
hm.. docker-py is failing on Janky; https://jenkins.dockerproject.org/job/Docker-PRs/55341/console

should not be related, but curious what happened there

```
19:02:58 ___________________ SwarmTest.test_init_swarm_with_ca_config ___________________
19:02:59 /docker-py/tests/integration/api_swarm_test.py:60: in test_init_swarm_with_ca_config
19:02:59     assert self.init_swarm(swarm_spec=spec)
19:02:59 /docker-py/tests/integration/base.py:128: in init_swarm
19:02:59     return self._init_swarm(self.client, **kwargs)
19:02:59 /docker-py/tests/integration/base.py:95: in _init_swarm
19:02:59     '127.0.0.1', listen_addr=helpers.swarm_listen_addr(), **kwargs
19:02:59 /docker-py/docker/utils/decorators.py:34: in wrapper
19:02:59     return f(self, *args, **kwargs)
19:02:59 /docker-py/docker/api/swarm.py:129: in init_swarm
19:02:59     self._raise_for_status(response)
19:02:59 /docker-py/docker/api/client.py:258: in _raise_for_status
19:02:59     raise create_api_error_from_http_exception(e)
19:02:59 /docker-py/docker/errors.py:31: in create_api_error_from_http_exception
19:02:59     raise cls(e, response=response, explanation=explanation)
19:02:59 E   APIError: 503 Server Error: Service Unavailable ("Swarm is encrypted and needs to be unlocked before it can be used. Please use "docker swarm unlock" to unlock it.")
```

**Pull request merged**
