### PR TITLE
[19.03 backport] ConstraintEnforcer fix

### PR DESCRIPTION
**Pull request by dperny**
Revendors docker/swarmkit to backport fixes made to the ConstraintEnforcer (see docker/swarmkit#2857)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Failures are due to Docker Hub returning different search results;

```
19:18:21 ----------------------------------------------------------------------
19:18:21 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
19:18:21 
```

fix is being worked on in https://github.com/moby/moby/pull/39243

**Comment by thaJeztah** [comment]
All other tests passed, so I'm bringing this one in

**Comment by jlhawn** [comment]
@thaJeztah @dperny was this merged into the `master` branch in this repository too? I couldn't find it by looking at the recent commits on `master`.

**Comment by thaJeztah** [comment]
No I don't think a PR was opened to get it upstream

**Comment by dperny** [comment]
right, right. forgot about vendoring into master.

**Pull request merged**
