### PR TITLE
[18.09 backport] Jenkinsfile updates, and add junit.xml for "integration"

### PR DESCRIPTION
**Pull request by thaJeztah**
Backports of:

- https://github.com/moby/moby/pull/39863 Jenkinsfile hack for auto-cancellation
- https://github.com/moby/moby/pull/39858 Jenkinsfile: create bundles for Windows stages
- SKIPPED: moby 39799 Remove go-check
- https://github.com/moby/moby/pull/39893 Jenkinsfile: shorten stage names for consistency and to fit Jenkins UI 
- https://github.com/moby/moby/pull/39802 integration: simplify parallel run destination
- https://github.com/moby/moby/pull/39724 Jenkinsfile: create junit.xml for integration tests
- https://github.com/moby/moby/pull/39789 Jenkinsfile: reduce CI time by disabling windows RS1
- https://github.com/moby/moby/pull/39932 Jenkinsfile: remove redundant -f Dockerfile
- https://github.com/moby/moby/pull/39957 Jenkinsfile: ensure all containers are cleaned up
- SKIPPED moby 39911 hack: have integration-cli use gotestsum codepath
- https://github.com/moby/moby/pull/39917 Zap a fixed windows folder, add build number to folder inside
- https://github.com/moby/moby/pull/39984 Jenkinsfile: move integration step cleanup to amd64 where it was intended to be
- https://github.com/moby/moby/pull/39990 Update links/references to transferred repositories
- https://github.com/moby/moby/pull/40035 Jenkinsfile: set repo and branch, to assist validate_diff()
- (skipped for now) moby/moby 39340 Buildkit-optimized dockerfile + buildx
    - relates to moby/moby 39512 Canonical Dockerfile
- (skipped for now) moby/moby 40049 Jenkinsfile: fix typo buidx -> buildx
- (skipped for now) moby/moby 40044 Dockerfile formatting changes and optimisations
- (skipped for now) moby/moby 40060 Makefile: force using buildkit if USE_BUILDX is not set
- (skipped for now) moby/moby 40059 Fix trick for `make BINDDIR=. shell` and `COPY .`
- (skipped for now) moby/moby 40089 Fix various issues with the "make buildx" target
- (skipped for now) moby/moby 40091 Make binary output targets use own build cmd
- (skipped for now) moby/moby /39678 [Carry 39595] Tailor CI for ARM, skip legacy integration 
- https://github.com/moby/moby/pull/40119 Jenkinsfile: set repo and branch for DCO check as well
- https://github.com/moby/moby/pull/38496 Add note to Dockerfile.windows to not change `FROM`
- https://github.com/moby/moby/pull/39879 hack/ci/windows.ps1: fix Go version check (due to trailing .0)
- https://github.com/moby/moby/pull/39888 Move GOPATH out from under the GO source tree

#### All cherry-picks were clean

```bash
# https://github.com/moby/moby/pull/39863 Jenkinsfile hack for auto-cancellation
git cherry-pick -s -S -x 85bcc524eaa86ea5dde0c7214d15658587863a4c

# https://github.com/moby/moby/pull/39858 Jenkinsfile: create bundles for Windows stages
git cherry-pick -s -S -x 6ee61f54935d77d3d5667b4a3ba8f0be6c3de23d \
	1fbadd76b7ceab6e5bb683a7471f5cae8e715495

# https://github.com/moby/moby/pull/39893 Jenkinsfile: shorten stage names for consistency and to fit Jenkins UI 
git cherry-pick -s -S -x c18f793f40c8692a06a73a8ed1b14b05091964f9

# https://github.com/moby/moby/pull/39802 integration: simplify parallel run destination
git cherry-pick -s -S -x 3262a69be6c582e4543199ddc54ebe2e306e3637

# https://github.com/moby/moby/pull/39724 Jenkinsfile: create junit.xml for integration tests
git cherry-pick -s -S -x f3be6b346f5300150dfa1de927880ea84440bb5b \
	d2e00d62e244b293b5b2459942b3a55447c191f3 \
	f007b0150a1559ab3ba34cd81832c7c9b4e8f78f \
	d723643dc38c18556ec5f7f0e97a8a594df545f7

# https://github.com/moby/moby/pull/39789 Jenkinsfile: reduce CI time by disabling windows RS1
git cherry-pick -s -S -x 039eb05ac87d52fe0b268c090f137eaa14754eed \
	e653943e8befaff83d6ace9b6f943f0cc8027ae4

# https://github.com/moby/moby/pull/39932 Jenkinsfile: remove redundant -f Dockerfile
git cherry-pick -s -S -x 64b3d12686e1a4ad4669e8c195cacafd76ea265c

# https://github.com/moby/moby/pull/39957 Jenkinsfile: ensure all containers are cleaned up
git cherry-pick -s -S -x f470698c2c10c2382080fab34f83088450fabdd6

# https://github.com/moby/moby/pull/39917 Zap a fixed windows folder, add build number to folder inside
git cherry-pick -s -S -x 48662075434da5a13b1316df1ac7488a81e4cf0a

# https://github.com/moby/moby/pull/39984 Jenkinsfile: move integration step cleanup to amd64 where it was intended to be
git cherry-pick -s -S -x f3d8b8ae74804ba6a0386186c1c65bd1d556075a

# https://github.com/moby/moby/pull/39990 Update links/references to transferred repositories
git cherry-pick -s -S -x b323c6e9aeb6c18b25cd77b6ecafc761785b8c65 \
	83fd212f2cb71aae2f4a5a60c893c2bd01e59b72 \
	5175ed54e58d2027e54571ef384eed54626f6c89

# https://github.com/moby/moby/pull/40035 Jenkinsfile: set repo and branch, to assist validate_diff()
git cherry-pick -s -S -x 7019b60d0d6f3d69e6ccf481ca0a912905a9c1d7

# https://github.com/moby/moby/pull/40119 Jenkinsfile: set repo and branch for DCO check as well
git cherry-pick -s -S -x 7c5fd83c22d9540b6e31393abdf62e54c4ff6060


# https://github.com/moby/moby/pull/38496 Add note to Dockerfile.windows to not change `FROM`
git cherry-pick -s -S -x 3bcf58236619f4c2902157ce4deaaaf44ca6f128

# https://github.com/moby/moby/pull/39879 hack/ci/windows.ps1: fix Go version check (due to trailing .0)
git cherry-pick -s -S -x 61450a651ba8fe4ef3cac284482a9495fc0b761d

# https://github.com/moby/moby/pull/39888 Move GOPATH out from under the GO source tree
git cherry-pick -s -S -x ecf91f0d7f90b2bd9fa048f2a800beaf613ac507

```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Failure on amd64; https://ci.docker.com/public/job/engine/job/PR-395/1/execution/node/199/log/?consoleFull


```
00:41:06.686  FAIL: check_test.go:347: DockerSwarmSuite.TearDownTest
00:41:06.686  
00:41:06.686  check_test.go:352:
00:41:06.686      d.Stop(c)
00:41:06.686  /go/src/github.com/docker/docker/internal/test/daemon/daemon.go:414:
00:41:06.686      t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
00:41:06.686  ... Error: Error while stopping the daemon d1512c423813a : remove /go/src/github.com/docker/docker/bundles/test-integration/DockerSwarmSuite.TestServiceLogs/d1512c423813a/docker.pid: no such file or directory
00:41:06.686  
00:41:06.686  
00:41:06.686  ----------------------------------------------------------------------
00:41:06.686  PANIC: docker_cli_service_logs_test.go:25: DockerSwarmSuite.TestServiceLogs
00:41:06.686  
00:41:06.686  Creating a new daemon at: /go/src/github.com/docker/docker/bundles/test-integration/DockerSwarmSuite.TestServiceLogs
00:41:06.686  [d1512c423813a] waiting for daemon to start
00:41:06.686  [d1512c423813a] daemon started
00:41:06.686  
00:41:06.686  waited for 2.318136901s (out of 30s)
00:41:06.686  log for "TestServiceLogs1": "TestServiceLogs1.1.ezmpntdpejqf@0f0c64a066f7    | hello1\n"
00:41:06.686  log for "TestServiceLogs2": "TestServiceLogs2.1.arivrz26cfa1@0f0c64a066f7    | hello2\n"
00:41:06.686  [d1512c423813a] daemon stop timeout
00:41:06.686  Attempt #2: daemon is still running with pid 13792
00:41:06.686  Attempt #3: daemon is still running with pid 13792
00:41:06.686  Attempt #4: daemon is still running with pid 13792
00:41:06.686  Attempt #5: daemon is still running with pid 13792
00:41:06.686  tried to interrupt daemon for 6 times, now try to kill it
00:41:06.686  ... Panic: Fixture has panicked (see related PANIC)
00:41:06.686  
```

**Comment by thaJeztah** [comment]
Unfortunately, due to the panic, there were no logs collected for that test

**Comment by thaJeztah** [comment]
Also need to add https://github.com/moby/moby/pull/40119, but perhaps we should get the ssh-agent changes in this branch as well

**Comment by thaJeztah** [comment]
Interesting; this test was originally failing on the PR that added the ARM64
stage, but it later was resolved; looks like there may be a bug somewhere,
and a fix in master that's not in the 18.09 branch;

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/engine/branches/PR-395/runs/4/nodes/273/log/?start=0

```
=== FAIL: arm64.integration.config TestTemplatedConfig (3.56s)
    config_test.go:188: Creating a new daemon at: /go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig
    daemon.go:302: [d4687ea09d50a] waiting for daemon to start
    daemon.go:334: [d4687ea09d50a] daemon started
    config_test.go:307: assertion failed: string "overlay on / type overlay (rw,relatime,lowerdir=/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/d4687ea09d50a/root/overlay2/l/6MTGPNTRAEJSN5DXGTYYXKKO5D:/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/d4687ea09d50a/root/overlay2/l/OVA7UXOYFT235NHT65JMJBH3JP,upperdir=/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/d4687ea09d50a/root/overlay2/7eda2408f02a0d46ac64d548fb7e9f90c8c47459a537afd0376f9aecd23db84a/diff,workdir=/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/d4687ea09d50a/root/overlay2/7eda2408f02a0d46ac64d548fb7e9f90c8c47459a537afd0376f9aecd23db84a/work)\nproc on /proc type proc (rw,nosuid,nodev,noexec,relatime)\ntmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)\ndevpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)\nsysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)\ntmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)\ncgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)\ncgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)\ncgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)\ncgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)\ncgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)\ncgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)\ncgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)\ncgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)\ncgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)\ncgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)\ncgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)\ncgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)\nmqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)\noverlay on /dev/init type overlay (ro,relatime,lowerdir=/var/lib/docker/overlay2/l/HQ7NUPJ3WGNI32ETTYCTYMESQ7:/var/lib/docker/overlay2/l/RBPLDVJZHKE3LF2J7QR56BKEHI:/var/lib/docker/overlay2/l/XJHAL2LMGWGBPBMC7QILUVNSNX:/var/lib/docker/overlay2/l/Z65ZYEYP7ZY7Z2O2WXLO3R4KLT:/var/lib/docker/overlay2/l/UIU7MKCSF4NDK5TTIYKYYIVHGV:/var/lib/docker/overlay2/l/KUWVYCU2VEYOMPUCZTKMXIRLAN:/var/lib/docker/overlay2/l/PYKF56GKA62PAETBSTYBLC3WUQ:/var/lib/docker/overlay2/l/NODOMPHUH63DVT5OL3KPDFP6YO:/var/lib/docker/overlay2/l/R5EOTX3ZQUA3UX3KKFYQNLZHY5:/var/lib/docker/overlay2/l/FCLTJS3Y54NKEGCPSADB27RNG5:/var/lib/docker/overlay2/l/YL3AIXQPCAHOOSYWMFPPO75KJ6:/var/lib/docker/overlay2/l/SFXJANQBKJUHRREXF66FP5RVYJ:/var/lib/docker/overlay2/l/T7IGWSJ6JKZF3Z4GZK4WKIG75I:/var/lib/docker/overlay2/l/L4NP7ZEGRHPEGC5ZL5E2AYOQTI:/var/lib/docker/overlay2/l/ACUKHUXAK7DMKKMGLOST7RCRTG:/var/lib/docker/overlay2/l/CPMDKJ6TXZ72KWSYKQFSO35KKO:/var/lib/docker/overlay2/l/P5M2IOBOY4RGURHNQA3S6SBRM4:/var/lib/docker/overlay2/l/TQTXLK2QXEYG2TP)\n" does not contain "tmpfs on /templated_config-TestTemplatedConfig type tmpfs"
    daemon.go:286: [d4687ea09d50a] exiting daemon
```


Failure on RS5 could be either a flake, or something missing in the Dockerfile or the `.ps1` scripts;

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/engine/branches/PR-395/runs/4/nodes/194/log/?start=0

```
SUCCESS: Specified value was saved.
INFO: Downloading git...
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred
during a WebClient request."
At line:1 char:1304
+ ... stem.Net.WebClient; $webClient.DownloadFile($source, $target); } } se ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE
   xception
    + FullyQualifiedErrorId : WebException
```

**Comment by thaJeztah** [comment]
Gonna move the ARM64 cherry-pick separate

**Review by andrewhsu — APPROVED** [review]
LGTM

**Pull request merged**
