### PR TITLE
[18.09 backport] fix panic on empty dockerfile

### PR DESCRIPTION
**Pull request by thaJeztah**
- bump buildkit 05766c5c21a1e528eeb1c3522b2f05493fe9ac47 (docker-18.09 branch)
  - moby/buildkit#952 [18.09 backport] Have parser error on dockerfiles without instructions
    - backport of moby/buildkit#771 Have parser error on dockerfiles without instructions
- https://github.com/moby/moby/pull/38487 Error on empty dockerfile
  - first two commits (last commit (vendor bump) is replaced with the bump above)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tonistiigi @LinuxMercedes ptal

**Comment by LinuxMercedes** [comment]
The z failure looks unrelated:

```
12:00:36 FAIL: docker_cli_pull_test.go:270: DockerSuite.TestPullWindowsImageFailsOnLinux
12:00:36 
12:00:36 docker_cli_pull_test.go:273:
12:00:36     c.Assert(err.Error(), checker.Contains, "cannot be used on this platform")
12:00:36 ... obtained string = "" +
12:00:36 ...     "\n" +
12:00:36 ...     "Command:  /usr/local/cli/docker pull microsoft/nanoserver\n" +
12:00:36 ...     "ExitCode: 1\n" +
12:00:36 ...     "Error:    exit status 1\n" +
12:00:36 ...     "Stdout:   Using default tag: latest\n" +
12:00:36 ...     "\n" +
12:00:36 ...     "Stderr:   Error response from daemon: manifest for microsoft/nanoserver:latest not found\n" +
12:00:36 ...     "\n" +
12:00:36 ...     "\n" +
12:00:36 ...     "Failures:\n" +
12:00:36 ...     "ExitCode was 1 expected 0\n" +
12:00:36 ...     "Expected no error"
12:00:36 ... substring string = "cannot be used on this platform"
```

**Comment by thaJeztah** [comment]
> The failures looks unrelated:

Ah, yes, I forgot the fix for that isn't merged yet; the fix for that is included in https://github.com/docker/engine/pull/198 😓

**Comment by LinuxMercedes** [comment]
Ah!

Looks good otherwise! :+1:

**Comment by thaJeztah** [comment]
rebased, now that https://github.com/docker/engine/pull/198 was merged

**Comment by LinuxMercedes** [comment]
Failures so far look flaky:
- z:  https://github.com/moby/moby/issues/37306 (`TestServiceRemoveKeepsIngressNetwork`)
- experimental: https://github.com/moby/moby/issues/38521

**Comment by LinuxMercedes** [comment]
Oh, that janky failure is related. You'd need to include https://github.com/moby/moby/pull/38524 or backport https://github.com/docker/docker-py/pull/2216 to whatever version of docker-py is included in this release.

**Comment by thaJeztah** [comment]
Oh, good catch thanks! opened a separate PR for that one https://github.com/docker/engine/pull/202

**Comment by thaJeztah** [comment]
rebased on top of https://github.com/docker/engine/pull/202 to get both changes in here

**Pull request merged**
